name: healthchecks

services:
  db:
    image: mariadb:10.4
    container_name: healthchecks_db
    volumes:
      - "healthchecks-db:/var/lib/mysql"
    environment:
      - "MYSQL_ALLOW_EMPTY_PASSWORD=yes"
      - "MYSQL_DATABASE"
      - "MYSQL_USER"
      - "MYSQL_PASSWORD"
    restart: always

  msmtpd:
    image: crazymax/msmtpd:latest
    container_name: healthchecks_msmtpd
    env_file:
      - "./msmtpd.env"
    environment:
      - "TZ"
    restart: always

  healthchecks:
    image: crazymax/healthchecks:latest
    container_name: healthchecks
    ports:
      - target: 8000
        published: 8000
        protocol: tcp
    volumes:
      - "healthchecks:/data"
    env_file:
      - "./healthchecks.env"
    environment:
      - "TZ"
      - "DB=mysql"
      - "DB_HOST=db"
      - "DB_NAME=${MYSQL_DATABASE}"
      - "DB_USER=${MYSQL_USER}"
      - "DB_PASSWORD=${MYSQL_PASSWORD}"
    restart: always

volumes:
  healthchecks:
  healthchecks-db:
